kind: pipeline
name: default
type: exec

platform:
  os: linux
  arch: arm

steps:
- name: mocha
  image: node
  commands:
  - npm ci
  - npm test

- name: package
  image: node
  commands:
  - npm pack

- name: distribute
  image: node
  commands:
  - whoami
  - pwd
  - echo 'continue from here!'